### ISSUE TITLE
Image size criteria

### ISSUE THREAD

**Issue by sabas** [hatnote/montage#3]
When voting for WLM Italy I encountered this photo which is smaller than the thumbnail, so the thumbnail generation gives a HTTP 400 answer.
https://commons.wikimedia.org/wiki/File:Biblioteca_Fortunata.jpg

(it's Image #87040)

Perhaps it would be nice to detect these edge cases setting an automated filter (there's a minimum resolution limit IIRC)

**Comment by papuass** [comment]
Noticed the same: https://commons.wikimedia.org/w/thumb.php?f=RigaRupniecibas9.jpg&w=800
Image is: 768 × 1024px

But we would want to filter out all small images anyway. And possibly images taken by me or other WLM organizers.

**Comment by yarl** [comment]
Right, I'll probably fix it today. 

> But we would want to filter out all small images anyway. And possibly images taken by me or other WLM organizers.

I believe we reject all images below 2Mpix during import. @mahmoud @slaporte: Italy was imported before this feature?

**Comment by papuass** [comment]
WLM Latvia contains images under 2Mpix.

**Comment by slaporte** [comment]
We have a backend function to filter out images by resolution (and a few other criteria) at the start of the round, but didn't enable it by default and it's not a configuration option in the UI. @yarl, we can set the config [like this](https://github.com/hatnote/montage/blob/master/run_server_test.py#L138) when creating a round.

I'll add options for filter at the end of the round too, and we should probably add a path for coordinators to see the files that were filtered.

**Comment by yarl** [comment]
Thumbnail size fix deployed on `beta`, now the thumbnial is 1024px wide, 800px wide, or original width if width is less than 800px.

Please reopen if persist.

**Comment by sabas** [comment]
@yarl gives the same error with the small pics, set it to (original - 1) px
Example 
https://commons.wikimedia.org/w/thumb.php?f=Vecchia_Partecipanza.jpg&w=513 => 400
https://commons.wikimedia.org/w/thumb.php?f=Vecchia_Partecipanza.jpg&w=512 => 200

**Comment by yarl** [comment]
Yeah sorry, fixed now, please check. Meme related ;)

![img](http://i.imgur.com/VdrGAZK.jpg)

**Comment by papuass** [comment]
I still get errors with files like https://commons.wikimedia.org/w/thumb.php?f=Skujenes_luter%C4%81%C5%86u_bazn%C4%ABca_3.jpg&w=1280

Width is 1280px.

**Comment by Jarry1250** [comment]
I just got problems with https://commons.wikimedia.org/w/thumb.php?f=Britishmuseum2.jpg&w=800
